name: check
on:
  workflow_dispatch:
  push:
    branches: "main"
    tags-ignore: ["**"]
  pull_request:
  schedule:
    - cron: "0 8 * * *"

concurrency:
  group: check-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: test ${{ matrix.py }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        py:
          - "3.12"
          - "3.11"
          - "3.10"
          - "3.9"
          - "3.8"
          - "3.7"
          - "pypy3.10"
          - "pypy3.7"
        os:
          - ubuntu-latest
          - windows-latest
          - macos-latest
    steps:
      - name: Setup python for tox
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install tox
        run: python -m pip install tox
      - name: Setup python for test ${{ matrix.py }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.py }}
      - name: Setup test suite
        run: tox r -e ${{ matrix.py }} --skip-missing-interpreters false -vv --notest
        env:
          FORCE_COLOR: "1"
      - name: Run test suite
        run: tox r -e ${{ matrix.py }} --skip-missing-interpreters false  --skip-pkg-install
        env:
          FORCE_COLOR: "1"
          PYTEST_ADDOPTS: "-vv --durations=20"
          CI_RUN: "yes"
          DIFF_AGAINST: HEAD

  check:
    name: tox env ${{ matrix.tox_env }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        tox_env:
          - type
          - dev
          - docs
          - pkg_meta
        os:
          - ubuntu-latest
          - windows-latest
        exclude:
          - { os: windows-latest, tox_env: pkg_meta } # would be the same
          - { os: ubuntu-latest, tox_env: docs } # runs on readthedocs.org already
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Install tox
        run: python -m pip install tox
      - name: Run check for ${{ matrix.tox_env }}
        run: tox -e ${{ matrix.tox_env }}
        env:
          UPGRADE_ADVISORY: "yes"
